# Generated by Django 3.1.4 on 2021-05-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(default=3750363511, max_length=32),
            preserve_default=False,
        ),
    ]
