# Generated by Django 3.1.4 on 2021-07-29 09:00

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210521_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.models.design_upload_append_image_file_path)),
            ],
        ),
    ]
