# Generated by Django 3.1.4 on 2021-09-08 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_supplier_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='rainking',
            new_name='ranking',
        ),
    ]
