# Generated by Django 3.1.4 on 2021-08-01 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='test',
        ),
    ]
