# Generated by Django 3.1.4 on 2021-09-17 11:33

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210908_0639'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=64)),
                ('image_front', models.ImageField(upload_to=core.models.product_image_file_path)),
                ('image_back', models.ImageField(upload_to=core.models.product_image_file_path)),
                ('image_side_left', models.ImageField(upload_to=core.models.product_image_file_path)),
                ('image_side_right', models.ImageField(upload_to=core.models.product_image_file_path)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
    ]
